name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend/nuxt-app
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run build

  auth-service:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/auth
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: python -m venv .venv && . .venv/bin/activate && pip install fastapi uvicorn[standard]
      - run: echo "Health check passes (install-only for now)"
