name: Runner Smoke Test

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/runner-smoke.yml"

permissions:
  contents: read

jobs:
  smoke:
    runs-on: [self-hosted, linux, afrotek]
    timeout-minutes: 5
    steps:
      - name: Show runner context
        shell: bash
        run: |
          echo "Runner name: ${RUNNER_NAME:-unknown}"
          echo "Runner OS: ${RUNNER_OS:-?} ${RUNNER_OS_VERSION:-?}"
          echo "PATH: $PATH"

      - name: Helpers
        id: env
        shell: bash
        run: |
          have() { command -v "$1" >/dev/null 2>&1; }
          echo "has_ip=$(have ip && echo yes || echo no)" >> "$GITHUB_OUTPUT"
          echo "has_free=$(have free && echo yes || echo no)" >> "$GITHUB_OUTPUT"
          echo "has_curl=$(have curl && echo yes || echo no)" >> "$GITHUB_OUTPUT"
          echo "has_jq=$(have jq && echo yes || echo no)" >> "$GITHUB_OUTPUT"
          echo "has_dotnet=$(have dotnet && echo yes || echo no)" >> "$GITHUB_OUTPUT"

      - name: System basics
        shell: bash
        run: |
          uname -a || true
          whoami || true
          id || true
          cat /etc/os-release || true
          df -h || true
          if command -v free >/dev/null 2>&1; then free -h; else echo "free not installed"; fi
          if command -v ip >/dev/null 2>&1; then ip -brief a; else echo "ip not installed"; fi

      - name: Toolchain checks
        shell: bash
        run: |
          node --version || echo "node not installed"
          npm --version || echo "npm not installed"
          pnpm --version || echo "pnpm not installed"
          yarn --version || echo "yarn not installed"
          docker --version || echo "docker not installed"
          git --version || echo "git not installed"
          dotnet --info || echo "dotnet not installed"
          jq --version || echo "jq not installed"

      - name: Network quick check (skip if curl missing)
        shell: bash
        run: |
          if command -v curl >/dev/null 2>&1; then
            for url in https://api.afrotek.co.za/health https://auth.afrotek.co.za/health; do
              echo "Checking $url"
              curl -fsSIL --max-time 5 "$url" || echo "Could not reach $url"
            done
          else
            echo "curl not installed; skipping network check"
          fi

      - name: ✅ Done
        run: echo "Runner OK"
